### ISSUE TITLE
polysemy-RandomFu is broken on ghc 9 

### ISSUE THREAD

**Issue by funketh** [adamConnerSax/polysemy-Extra#2]
might be similiar to https://github.com/polysemy-research/polysemy-zoo/pull/70
```hs
[3 of 3] Compiling Polysemy.ConstraintAbsorber.MonadRandom
                                 
/home/theo/prj/polysemy-Extra/polysemy-RandomFu/src/Polysemy/ConstraintAbsorber/MonadRandom.hs:22:15: error:
    * Could not deduce: (Member RandomFu r0) 
      Fix:                       
        add (Member RandomFu r0) to the context of
          the type signature     
    * In the first argument of `RandomDict', namely `getRandomPrim'
      In the third argument of `absorbWithSem', namely
        `(RandomDict getRandomPrim)'
      In the expression:         
        absorbWithSem            
          @R.MonadRandom @Action (RandomDict getRandomPrim) (Sub Dict)
   |                             
22 |   (RandomDict getRandomPrim)
   |               ^^^^^^^^^^^^^ 
                                 
/home/theo/prj/polysemy-Extra/polysemy-RandomFu/src/Polysemy/ConstraintAbsorber/MonadRandom.hs:23:8: error:
    * Could not deduce (R.MonadRandom (Action (Sem r) s))
        arising from a use of `Dict'
      from the context: Member RandomFu r
        bound by the type signature for:
                   absorbMonadRandom :: forall (r :: [(* -> *) -> * -> *]) a.
                                        Member RandomFu r =>
                                        (R.MonadRandom (Sem r) => Sem r a) -> Sem r a
        at src/Polysemy/ConstraintAbsorber/MonadRandom.hs:(19,1)-(20,50)
      or from: Reifies s (RandomDict (Sem r0))
        bound by a type expected by the context:
                   Reifies s (RandomDict (Sem r0)) =>
                   Dict (R.MonadRandom (Action (Sem r) s))
        at src/Polysemy/ConstraintAbsorber/MonadRandom.hs:23:8-11
    * In the first argument of `Sub', namely `Dict'
      In the fourth argument of `absorbWithSem', namely `(Sub Dict)'
      In the expression:         
        absorbWithSem            
          @R.MonadRandom @Action (RandomDict getRandomPrim) (Sub Dict)
   |                             
23 |   (Sub Dict)                
   |        ^^^^                 
```
The `stack.yaml` I used:
```yml
compiler: ghc-9.0.1
resolver: nightly-2020-05-07

allow-newer: true

packages:
- ./polysemy-RandomFu

extra-deps:
- atomic-primops-0.8.4
- compact-0.2.0.0
- flexible-defaults-0.0.3
- ghc-tcplugins-extra-0.4.1
- MonadRandom-0.5.3
- random-1.2.0
- random-source-0.3.0.11
- rvar-0.2.0.6
- splitmix-0.1.0.3
- syb-0.7.2.1
- th-abstraction-0.4.2.0
- QuickCheck-2.14.2
# GHC 9 patches (not yet on hackage)
- github: polysemy-research/polysemy
  commit: 09c65bdae9c9ce50a55c7ee2ab9681916f09f4c3
  subdirs: [., polysemy-plugin]
- github: polysemy-research/polysemy-zoo
  commit: a93ec969d7efd397696a5495afe2e4fa0c509d6f
- github: haskell-numerics/random-fu
  commit: 2d38294582ba211df6a5a2b7f7a2c5e71038b0e7
  subdirs: [random-fu]
- github: mokus0/th-extras
  commit: 57a97b4df128eb7b360e8ab9c5759392de8d1659
```
